language: generic 
sudo: required
services:
 - docker

before_install:
 - docker build -t mancforever/devops -f Dockerfile.dev .

script:
 - docker run -e CI=true mancforever/docker-react npm run test
